// Capital city, primary language, and land area (km²) per ISO 3166-1
// alpha-3 code. Extracted once from the `world-countries` package (not a
// runtime dependency) with Korean names filled in by hand, since that
// package only has English names. Population isn't included here since
// it goes stale quickly - CountryInfoPanel fetches it live from the World
// Bank API instead.
export const GEO_INFO: Record<
  string,
  { capitalKo: string; capitalEn: string; langKo: string; area: number | null }
> = {
  ABW: { capitalKo: "오라녜스타드", capitalEn: "Oranjestad", langKo: "네덜란드어", area: 180 },
  AFG: { capitalKo: "카불", capitalEn: "Kabul", langKo: "다리어", area: 652230 },
  AGO: { capitalKo: "루안다", capitalEn: "Luanda", langKo: "포르투갈어", area: 1246700 },
  AIA: { capitalKo: "더밸리", capitalEn: "The Valley", langKo: "영어", area: 91 },
  ALA: { capitalKo: "마리에함", capitalEn: "Mariehamn", langKo: "스웨덴어", area: 1580 },
  ALB: { capitalKo: "티라나", capitalEn: "Tirana", langKo: "알바니아어", area: 28748 },
  AND: { capitalKo: "안도라라베야", capitalEn: "Andorra la Vella", langKo: "카탈루냐어", area: 468 },
  ARE: { capitalKo: "아부다비", capitalEn: "Abu Dhabi", langKo: "아랍어", area: 83600 },
  ARG: { capitalKo: "부에노스아이레스", capitalEn: "Buenos Aires", langKo: "스페인어", area: 2780400 },
  ARM: { capitalKo: "예레반", capitalEn: "Yerevan", langKo: "아르메니아어", area: 29743 },
  ASM: { capitalKo: "파고파고", capitalEn: "Pago Pago", langKo: "영어", area: 199 },
  ATF: { capitalKo: "포르토프랑세", capitalEn: "Port-aux-Français", langKo: "프랑스어", area: 7747 },
  ATG: { capitalKo: "세인트존스", capitalEn: "Saint John's", langKo: "영어", area: 442 },
  AUS: { capitalKo: "캔버라", capitalEn: "Canberra", langKo: "영어", area: 7692024 },
  AUT: { capitalKo: "빈", capitalEn: "Vienna", langKo: "독일어", area: 83871 },
  AZE: { capitalKo: "바쿠", capitalEn: "Baku", langKo: "아제르바이잔어", area: 86600 },
  BDI: { capitalKo: "기테가", capitalEn: "Gitega", langKo: "프랑스어", area: 27834 },
  BEL: { capitalKo: "브뤼셀", capitalEn: "Brussels", langKo: "네덜란드어", area: 30528 },
  BEN: { capitalKo: "포르토노보", capitalEn: "Porto-Novo", langKo: "프랑스어", area: 112622 },
  BFA: { capitalKo: "와가두구", capitalEn: "Ouagadougou", langKo: "프랑스어", area: 272967 },
  BGD: { capitalKo: "다카", capitalEn: "Dhaka", langKo: "벵골어", area: 147570 },
  BGR: { capitalKo: "소피아", capitalEn: "Sofia", langKo: "불가리아어", area: 110879 },
  BHR: { capitalKo: "마나마", capitalEn: "Manama", langKo: "아랍어", area: 765 },
  BHS: { capitalKo: "나소", capitalEn: "Nassau", langKo: "영어", area: 13943 },
  BIH: { capitalKo: "사라예보", capitalEn: "Sarajevo", langKo: "보스니아어", area: 51209 },
  BLM: { capitalKo: "구스타비아", capitalEn: "Gustavia", langKo: "프랑스어", area: 21 },
  SHN: { capitalKo: "제임스타운", capitalEn: "Jamestown", langKo: "영어", area: 394 },
  BLR: { capitalKo: "민스크", capitalEn: "Minsk", langKo: "벨라루스어", area: 207600 },
  BLZ: { capitalKo: "벨모판", capitalEn: "Belmopan", langKo: "벨리즈 크리올어", area: 22966 },
  BMU: { capitalKo: "해밀턴", capitalEn: "Hamilton", langKo: "영어", area: 54 },
  BOL: { capitalKo: "수크레", capitalEn: "Sucre", langKo: "스페인어", area: 1098581 },
  BES: { capitalKo: "크랄렌데이크", capitalEn: "Kralendijk", langKo: "영어", area: 328 },
  BRA: { capitalKo: "브라질리아", capitalEn: "Brasília", langKo: "포르투갈어", area: 8515767 },
  BRB: { capitalKo: "브리지타운", capitalEn: "Bridgetown", langKo: "영어", area: 430 },
  BRN: { capitalKo: "반다르스리브가완", capitalEn: "Bandar Seri Begawan", langKo: "말레이어", area: 5765 },
  BTN: { capitalKo: "팀부", capitalEn: "Thimphu", langKo: "종카어", area: 38394 },
  BWA: { capitalKo: "가보로네", capitalEn: "Gaborone", langKo: "영어", area: 582000 },
  CAF: { capitalKo: "방기", capitalEn: "Bangui", langKo: "프랑스어", area: 622984 },
  CAN: { capitalKo: "오타와", capitalEn: "Ottawa", langKo: "영어", area: 9984670 },
  CCK: { capitalKo: "웨스트섬", capitalEn: "West Island", langKo: "영어", area: 14 },
  CHE: { capitalKo: "베른", capitalEn: "Bern", langKo: "독일어", area: 41284 },
  CHL: { capitalKo: "산티아고", capitalEn: "Santiago", langKo: "스페인어", area: 756102 },
  CHN: { capitalKo: "베이징", capitalEn: "Beijing", langKo: "중국어", area: 9706961 },
  CIV: { capitalKo: "야무수크로", capitalEn: "Yamoussoukro", langKo: "프랑스어", area: 322463 },
  CMR: { capitalKo: "야운데", capitalEn: "Yaoundé", langKo: "프랑스어", area: 475442 },
  COD: { capitalKo: "킨샤사", capitalEn: "Kinshasa", langKo: "프랑스어", area: 2344858 },
  COG: { capitalKo: "브라자빌", capitalEn: "Brazzaville", langKo: "프랑스어", area: 342000 },
  COK: { capitalKo: "아바루아", capitalEn: "Avarua", langKo: "영어", area: 236 },
  COL: { capitalKo: "보고타", capitalEn: "Bogotá", langKo: "스페인어", area: 1141748 },
  COM: { capitalKo: "모로니", capitalEn: "Moroni", langKo: "아랍어", area: 1862 },
  CPV: { capitalKo: "프라이아", capitalEn: "Praia", langKo: "포르투갈어", area: 4033 },
  CRI: { capitalKo: "산호세", capitalEn: "San José", langKo: "스페인어", area: 51100 },
  CUB: { capitalKo: "아바나", capitalEn: "Havana", langKo: "스페인어", area: 109884 },
  CUW: { capitalKo: "빌렘스타드", capitalEn: "Willemstad", langKo: "영어", area: 444 },
  CXR: { capitalKo: "플라잉피시코브", capitalEn: "Flying Fish Cove", langKo: "영어", area: 135 },
  CYM: { capitalKo: "조지타운", capitalEn: "George Town", langKo: "영어", area: 264 },
  CYP: { capitalKo: "니코시아", capitalEn: "Nicosia", langKo: "그리스어", area: 9251 },
  CZE: { capitalKo: "프라하", capitalEn: "Prague", langKo: "체코어", area: 78865 },
  DEU: { capitalKo: "베를린", capitalEn: "Berlin", langKo: "독일어", area: 357114 },
  DJI: { capitalKo: "지부티", capitalEn: "Djibouti", langKo: "아랍어", area: 23200 },
  DMA: { capitalKo: "로조", capitalEn: "Roseau", langKo: "영어", area: 751 },
  DNK: { capitalKo: "코펜하겐", capitalEn: "Copenhagen", langKo: "덴마크어", area: 43094 },
  DOM: { capitalKo: "산토도밍고", capitalEn: "Santo Domingo", langKo: "스페인어", area: 48671 },
  DZA: { capitalKo: "알제", capitalEn: "Algiers", langKo: "아랍어", area: 2381741 },
  ECU: { capitalKo: "키토", capitalEn: "Quito", langKo: "스페인어", area: 276841 },
  EGY: { capitalKo: "카이로", capitalEn: "Cairo", langKo: "아랍어", area: 1002450 },
  ERI: { capitalKo: "아스마라", capitalEn: "Asmara", langKo: "아랍어", area: 117600 },
  ESH: { capitalKo: "라윤", capitalEn: "El Aaiún", langKo: "아랍어", area: 266000 },
  ESP: { capitalKo: "마드리드", capitalEn: "Madrid", langKo: "스페인어", area: 505992 },
  EST: { capitalKo: "탈린", capitalEn: "Tallinn", langKo: "에스토니아어", area: 45227 },
  ETH: { capitalKo: "아디스아바바", capitalEn: "Addis Ababa", langKo: "암하라어", area: 1104300 },
  FIN: { capitalKo: "헬싱키", capitalEn: "Helsinki", langKo: "핀란드어", area: 338424 },
  FJI: { capitalKo: "수바", capitalEn: "Suva", langKo: "영어", area: 18272 },
  FLK: { capitalKo: "스탠리", capitalEn: "Stanley", langKo: "영어", area: 12173 },
  FRA: { capitalKo: "파리", capitalEn: "Paris", langKo: "프랑스어", area: 551695 },
  FRO: { capitalKo: "토르스하운", capitalEn: "Tórshavn", langKo: "덴마크어", area: 1393 },
  FSM: { capitalKo: "팔리키르", capitalEn: "Palikir", langKo: "영어", area: 702 },
  GAB: { capitalKo: "리브르빌", capitalEn: "Libreville", langKo: "프랑스어", area: 267668 },
  GBR: { capitalKo: "런던", capitalEn: "London", langKo: "영어", area: 242900 },
  GEO: { capitalKo: "트빌리시", capitalEn: "Tbilisi", langKo: "조지아어", area: 69700 },
  GGY: { capitalKo: "세인트피터포트", capitalEn: "St. Peter Port", langKo: "영어", area: 78 },
  GHA: { capitalKo: "아크라", capitalEn: "Accra", langKo: "영어", area: 238533 },
  GIB: { capitalKo: "지브롤터", capitalEn: "Gibraltar", langKo: "영어", area: 6 },
  GIN: { capitalKo: "코나크리", capitalEn: "Conakry", langKo: "프랑스어", area: 245857 },
  GLP: { capitalKo: "바스테르", capitalEn: "Basse-Terre", langKo: "프랑스어", area: 1628 },
  GMB: { capitalKo: "반줄", capitalEn: "Banjul", langKo: "영어", area: 10689 },
  GNB: { capitalKo: "비사우", capitalEn: "Bissau", langKo: "포르투갈어", area: 36125 },
  GNQ: { capitalKo: "말라보", capitalEn: "Malabo", langKo: "프랑스어", area: 28051 },
  GRC: { capitalKo: "아테네", capitalEn: "Athens", langKo: "그리스어", area: 131990 },
  GRD: { capitalKo: "세인트조지스", capitalEn: "St. George's", langKo: "영어", area: 344 },
  GRL: { capitalKo: "누크", capitalEn: "Nuuk", langKo: "그린란드어", area: 2166086 },
  GTM: { capitalKo: "과테말라시티", capitalEn: "Guatemala City", langKo: "스페인어", area: 108889 },
  GUF: { capitalKo: "카옌", capitalEn: "Cayenne", langKo: "프랑스어", area: 83534 },
  GUM: { capitalKo: "하갓냐", capitalEn: "Hagåtña", langKo: "차모로어", area: 549 },
  GUY: { capitalKo: "조지타운", capitalEn: "Georgetown", langKo: "영어", area: 214969 },
  HKG: { capitalKo: "빅토리아시티", capitalEn: "City of Victoria", langKo: "영어", area: 1104 },
  HND: { capitalKo: "테구시갈파", capitalEn: "Tegucigalpa", langKo: "스페인어", area: 112492 },
  HRV: { capitalKo: "자그레브", capitalEn: "Zagreb", langKo: "크로아티아어", area: 56594 },
  HTI: { capitalKo: "포르토프랭스", capitalEn: "Port-au-Prince", langKo: "프랑스어", area: 27750 },
  HUN: { capitalKo: "부다페스트", capitalEn: "Budapest", langKo: "헝가리어", area: 93028 },
  IDN: { capitalKo: "자카르타", capitalEn: "Jakarta", langKo: "인도네시아어", area: 1904569 },
  IMN: { capitalKo: "더글러스", capitalEn: "Douglas", langKo: "영어", area: 572 },
  IND: { capitalKo: "뉴델리", capitalEn: "New Delhi", langKo: "힌디어", area: 3287590 },
  IOT: { capitalKo: "디에고가르시아", capitalEn: "Diego Garcia", langKo: "영어", area: 60 },
  IRL: { capitalKo: "더블린", capitalEn: "Dublin", langKo: "영어", area: 70273 },
  IRN: { capitalKo: "테헤란", capitalEn: "Tehran", langKo: "페르시아어", area: 1648195 },
  IRQ: { capitalKo: "바그다드", capitalEn: "Baghdad", langKo: "아랍어", area: 438317 },
  ISL: { capitalKo: "레이캬비크", capitalEn: "Reykjavik", langKo: "아이슬란드어", area: 103000 },
  ISR: { capitalKo: "예루살렘", capitalEn: "Jerusalem", langKo: "히브리어", area: 20770 },
  ITA: { capitalKo: "로마", capitalEn: "Rome", langKo: "이탈리아어", area: 301336 },
  JAM: { capitalKo: "킹스턴", capitalEn: "Kingston", langKo: "영어", area: 10991 },
  JEY: { capitalKo: "세인트헬리어", capitalEn: "Saint Helier", langKo: "영어", area: 116 },
  JOR: { capitalKo: "암만", capitalEn: "Amman", langKo: "아랍어", area: 89342 },
  JPN: { capitalKo: "도쿄", capitalEn: "Tokyo", langKo: "일본어", area: 377930 },
  KAZ: { capitalKo: "아스타나", capitalEn: "Astana", langKo: "카자흐어", area: 2724900 },
  KEN: { capitalKo: "나이로비", capitalEn: "Nairobi", langKo: "스와힐리어", area: 580367 },
  KGZ: { capitalKo: "비슈케크", capitalEn: "Bishkek", langKo: "키르기스어", area: 199951 },
  KHM: { capitalKo: "프놈펜", capitalEn: "Phnom Penh", langKo: "크메르어", area: 181035 },
  KIR: { capitalKo: "사우스타라와", capitalEn: "South Tarawa", langKo: "영어", area: 811 },
  KNA: { capitalKo: "바스테르", capitalEn: "Basseterre", langKo: "영어", area: 261 },
  KOR: { capitalKo: "서울", capitalEn: "Seoul", langKo: "한국어", area: 100210 },
  UNK: { capitalKo: "프리슈티나", capitalEn: "Pristina", langKo: "알바니아어", area: 10908 },
  KWT: { capitalKo: "쿠웨이트시티", capitalEn: "Kuwait City", langKo: "아랍어", area: 17818 },
  LAO: { capitalKo: "비엔티안", capitalEn: "Vientiane", langKo: "라오어", area: 236800 },
  LBN: { capitalKo: "베이루트", capitalEn: "Beirut", langKo: "아랍어", area: 10452 },
  LBR: { capitalKo: "몬로비아", capitalEn: "Monrovia", langKo: "영어", area: 111369 },
  LBY: { capitalKo: "트리폴리", capitalEn: "Tripoli", langKo: "아랍어", area: 1759540 },
  LCA: { capitalKo: "캐스트리스", capitalEn: "Castries", langKo: "영어", area: 616 },
  LIE: { capitalKo: "파두츠", capitalEn: "Vaduz", langKo: "독일어", area: 160 },
  LKA: { capitalKo: "콜롬보", capitalEn: "Colombo", langKo: "신할라어", area: 65610 },
  LSO: { capitalKo: "마세루", capitalEn: "Maseru", langKo: "영어", area: 30355 },
  LTU: { capitalKo: "빌뉴스", capitalEn: "Vilnius", langKo: "리투아니아어", area: 65300 },
  LUX: { capitalKo: "룩셈부르크", capitalEn: "Luxembourg", langKo: "독일어", area: 2586 },
  LVA: { capitalKo: "리가", capitalEn: "Riga", langKo: "라트비아어", area: 64559 },
  MAF: { capitalKo: "마리고", capitalEn: "Marigot", langKo: "프랑스어", area: 53 },
  MAR: { capitalKo: "라바트", capitalEn: "Rabat", langKo: "아랍어", area: 446550 },
  MCO: { capitalKo: "모나코", capitalEn: "Monaco", langKo: "프랑스어", area: 2 },
  MDA: { capitalKo: "키시너우", capitalEn: "Chișinău", langKo: "몰도바어", area: 33846 },
  MDG: { capitalKo: "안타나나리보", capitalEn: "Antananarivo", langKo: "프랑스어", area: 587041 },
  MDV: { capitalKo: "말레", capitalEn: "Malé", langKo: "디베히어", area: 300 },
  MEX: { capitalKo: "멕시코시티", capitalEn: "Mexico City", langKo: "스페인어", area: 1964375 },
  MHL: { capitalKo: "마주로", capitalEn: "Majuro", langKo: "영어", area: 181 },
  MKD: { capitalKo: "스코페", capitalEn: "Skopje", langKo: "마케도니아어", area: 25713 },
  MLI: { capitalKo: "바마코", capitalEn: "Bamako", langKo: "프랑스어", area: 1240192 },
  MLT: { capitalKo: "발레타", capitalEn: "Valletta", langKo: "영어", area: 316 },
  MMR: { capitalKo: "네피도", capitalEn: "Naypyidaw", langKo: "미얀마어", area: 676578 },
  MNE: { capitalKo: "포드고리차", capitalEn: "Podgorica", langKo: "몬테네그로어", area: 13812 },
  MNG: { capitalKo: "울란바토르", capitalEn: "Ulan Bator", langKo: "몽골어", area: 1564110 },
  MNP: { capitalKo: "사이판", capitalEn: "Saipan", langKo: "캐롤라인어", area: 464 },
  MOZ: { capitalKo: "마푸투", capitalEn: "Maputo", langKo: "포르투갈어", area: 801590 },
  MRT: { capitalKo: "누악쇼트", capitalEn: "Nouakchott", langKo: "아랍어", area: 1030700 },
  MSR: { capitalKo: "플리머스", capitalEn: "Plymouth", langKo: "영어", area: 102 },
  MTQ: { capitalKo: "포르드프랑스", capitalEn: "Fort-de-France", langKo: "프랑스어", area: 1128 },
  MUS: { capitalKo: "포트루이스", capitalEn: "Port Louis", langKo: "영어", area: 2040 },
  MWI: { capitalKo: "릴롱궤", capitalEn: "Lilongwe", langKo: "영어", area: 118484 },
  MYS: { capitalKo: "쿠알라룸푸르", capitalEn: "Kuala Lumpur", langKo: "말레이어", area: 330803 },
  MYT: { capitalKo: "마무주", capitalEn: "Mamoudzou", langKo: "프랑스어", area: 374 },
  NAM: { capitalKo: "빈트후크", capitalEn: "Windhoek", langKo: "영어", area: 825615 },
  NCL: { capitalKo: "누메아", capitalEn: "Nouméa", langKo: "프랑스어", area: 18575 },
  NER: { capitalKo: "니아메", capitalEn: "Niamey", langKo: "프랑스어", area: 1267000 },
  NFK: { capitalKo: "킹스턴", capitalEn: "Kingston", langKo: "영어", area: 36 },
  NGA: { capitalKo: "아부자", capitalEn: "Abuja", langKo: "영어", area: 923768 },
  NIC: { capitalKo: "마나과", capitalEn: "Managua", langKo: "스페인어", area: 130373 },
  NIU: { capitalKo: "알로피", capitalEn: "Alofi", langKo: "영어", area: 260 },
  NLD: { capitalKo: "암스테르담", capitalEn: "Amsterdam", langKo: "네덜란드어", area: 41850 },
  NOR: { capitalKo: "오슬로", capitalEn: "Oslo", langKo: "노르웨이어", area: 323802 },
  NPL: { capitalKo: "카트만두", capitalEn: "Kathmandu", langKo: "네팔어", area: 147181 },
  NRU: { capitalKo: "야렌", capitalEn: "Yaren", langKo: "영어", area: 21 },
  NZL: { capitalKo: "웰링턴", capitalEn: "Wellington", langKo: "영어", area: 270467 },
  OMN: { capitalKo: "무스카트", capitalEn: "Muscat", langKo: "아랍어", area: 309500 },
  PAK: { capitalKo: "이슬라마바드", capitalEn: "Islamabad", langKo: "우르두어", area: 881912 },
  PAN: { capitalKo: "파나마시티", capitalEn: "Panama City", langKo: "스페인어", area: 75417 },
  PCN: { capitalKo: "애덤스타운", capitalEn: "Adamstown", langKo: "영어", area: 47 },
  PER: { capitalKo: "리마", capitalEn: "Lima", langKo: "스페인어", area: 1285216 },
  PHL: { capitalKo: "마닐라", capitalEn: "Manila", langKo: "필리핀어", area: 342353 },
  PLW: { capitalKo: "응게룰무드", capitalEn: "Ngerulmud", langKo: "영어", area: 459 },
  PNG: { capitalKo: "포트모르즈비", capitalEn: "Port Moresby", langKo: "영어", area: 462840 },
  POL: { capitalKo: "바르샤바", capitalEn: "Warsaw", langKo: "폴란드어", area: 312679 },
  PRI: { capitalKo: "산후안", capitalEn: "San Juan", langKo: "영어", area: 8870 },
  PRK: { capitalKo: "평양", capitalEn: "Pyongyang", langKo: "한국어", area: 120538 },
  PRT: { capitalKo: "리스본", capitalEn: "Lisbon", langKo: "포르투갈어", area: 92090 },
  PRY: { capitalKo: "아순시온", capitalEn: "Asunción", langKo: "스페인어", area: 406752 },
  PSE: { capitalKo: "라말라", capitalEn: "Ramallah", langKo: "아랍어", area: 6220 },
  PYF: { capitalKo: "파페에테", capitalEn: "Papeetē", langKo: "프랑스어", area: 4167 },
  QAT: { capitalKo: "도하", capitalEn: "Doha", langKo: "아랍어", area: 11586 },
  REU: { capitalKo: "생드니", capitalEn: "Saint-Denis", langKo: "프랑스어", area: 2511 },
  ROU: { capitalKo: "부쿠레슈티", capitalEn: "Bucharest", langKo: "루마니아어", area: 238391 },
  RUS: { capitalKo: "모스크바", capitalEn: "Moscow", langKo: "러시아어", area: 17098242 },
  RWA: { capitalKo: "키갈리", capitalEn: "Kigali", langKo: "영어", area: 26338 },
  SAU: { capitalKo: "리야드", capitalEn: "Riyadh", langKo: "아랍어", area: 2149690 },
  SDN: { capitalKo: "하르툼", capitalEn: "Khartoum", langKo: "아랍어", area: 1886068 },
  SEN: { capitalKo: "다카르", capitalEn: "Dakar", langKo: "프랑스어", area: 196722 },
  SGP: { capitalKo: "싱가포르", capitalEn: "Singapore", langKo: "영어", area: 710 },
  SGS: { capitalKo: "킹에드워드포인트", capitalEn: "King Edward Point", langKo: "영어", area: 3903 },
  SJM: { capitalKo: "롱위에아르뷔엔", capitalEn: "Longyearbyen", langKo: "노르웨이어", area: null },
  SLB: { capitalKo: "호니아라", capitalEn: "Honiara", langKo: "영어", area: 28896 },
  SLE: { capitalKo: "프리타운", capitalEn: "Freetown", langKo: "영어", area: 71740 },
  SLV: { capitalKo: "산살바도르", capitalEn: "San Salvador", langKo: "스페인어", area: 21041 },
  SMR: { capitalKo: "산마리노시티", capitalEn: "City of San Marino", langKo: "이탈리아어", area: 61 },
  SOM: { capitalKo: "모가디슈", capitalEn: "Mogadishu", langKo: "아랍어", area: 637657 },
  SPM: { capitalKo: "생피에르", capitalEn: "Saint-Pierre", langKo: "프랑스어", area: 242 },
  SRB: { capitalKo: "베오그라드", capitalEn: "Belgrade", langKo: "세르비아어", area: 88361 },
  SSD: { capitalKo: "주바", capitalEn: "Juba", langKo: "영어", area: 619745 },
  STP: { capitalKo: "상투메", capitalEn: "São Tomé", langKo: "포르투갈어", area: 964 },
  SUR: { capitalKo: "파라마리보", capitalEn: "Paramaribo", langKo: "네덜란드어", area: 163820 },
  SVK: { capitalKo: "브라티슬라바", capitalEn: "Bratislava", langKo: "슬로바키아어", area: 49037 },
  SVN: { capitalKo: "류블랴나", capitalEn: "Ljubljana", langKo: "슬로베니아어", area: 20273 },
  SWE: { capitalKo: "스톡홀름", capitalEn: "Stockholm", langKo: "스웨덴어", area: 450295 },
  SWZ: { capitalKo: "로밤바", capitalEn: "Lobamba", langKo: "영어", area: 17364 },
  SXM: { capitalKo: "필립스뷔르흐", capitalEn: "Philipsburg", langKo: "영어", area: 34 },
  SYC: { capitalKo: "빅토리아", capitalEn: "Victoria", langKo: "세이셸 크리올어", area: 452 },
  SYR: { capitalKo: "다마스쿠스", capitalEn: "Damascus", langKo: "아랍어", area: 185180 },
  TCA: { capitalKo: "코크번타운", capitalEn: "Cockburn Town", langKo: "영어", area: 948 },
  TCD: { capitalKo: "은자메나", capitalEn: "N'Djamena", langKo: "아랍어", area: 1284000 },
  TGO: { capitalKo: "로메", capitalEn: "Lomé", langKo: "프랑스어", area: 56785 },
  THA: { capitalKo: "방콕", capitalEn: "Bangkok", langKo: "태국어", area: 513120 },
  TJK: { capitalKo: "두샨베", capitalEn: "Dushanbe", langKo: "타지크어", area: 143100 },
  TKL: { capitalKo: "파카오포", capitalEn: "Fakaofo", langKo: "영어", area: 12 },
  TKM: { capitalKo: "아시가바트", capitalEn: "Ashgabat", langKo: "투르크멘어", area: 488100 },
  TLS: { capitalKo: "딜리", capitalEn: "Dili", langKo: "포르투갈어", area: 14874 },
  TON: { capitalKo: "누쿠알로파", capitalEn: "Nuku'alofa", langKo: "영어", area: 747 },
  TTO: { capitalKo: "포트오브스페인", capitalEn: "Port of Spain", langKo: "영어", area: 5130 },
  TUN: { capitalKo: "튀니스", capitalEn: "Tunis", langKo: "아랍어", area: 163610 },
  TUR: { capitalKo: "앙카라", capitalEn: "Ankara", langKo: "터키어", area: 783562 },
  TUV: { capitalKo: "푸나푸티", capitalEn: "Funafuti", langKo: "영어", area: 26 },
  TWN: { capitalKo: "타이베이", capitalEn: "Taipei", langKo: "중국어", area: 36193 },
  TZA: { capitalKo: "도도마", capitalEn: "Dodoma", langKo: "스와힐리어", area: 945087 },
  UGA: { capitalKo: "캄팔라", capitalEn: "Kampala", langKo: "영어", area: 241550 },
  UKR: { capitalKo: "키이우", capitalEn: "Kyiv", langKo: "우크라이나어", area: 603500 },
  URY: { capitalKo: "몬테비데오", capitalEn: "Montevideo", langKo: "스페인어", area: 181034 },
  USA: { capitalKo: "워싱턴 D.C.", capitalEn: "Washington D.C.", langKo: "영어", area: 9372610 },
  UZB: { capitalKo: "타슈켄트", capitalEn: "Tashkent", langKo: "우즈베크어", area: 447400 },
  VAT: { capitalKo: "바티칸시티", capitalEn: "Vatican City", langKo: "이탈리아어", area: 0 },
  VCT: { capitalKo: "킹스타운", capitalEn: "Kingstown", langKo: "영어", area: 389 },
  VEN: { capitalKo: "카라카스", capitalEn: "Caracas", langKo: "스페인어", area: 916445 },
  VGB: { capitalKo: "로드타운", capitalEn: "Road Town", langKo: "영어", area: 151 },
  VIR: { capitalKo: "샬럿아말리에", capitalEn: "Charlotte Amalie", langKo: "영어", area: 347 },
  VNM: { capitalKo: "하노이", capitalEn: "Hanoi", langKo: "베트남어", area: 331212 },
  VUT: { capitalKo: "포트빌라", capitalEn: "Port Vila", langKo: "비슬라마어", area: 12189 },
  WLF: { capitalKo: "마타우투", capitalEn: "Mata-Utu", langKo: "프랑스어", area: 142 },
  WSM: { capitalKo: "아피아", capitalEn: "Apia", langKo: "영어", area: 2842 },
  YEM: { capitalKo: "사나", capitalEn: "Sana'a", langKo: "아랍어", area: 527968 },
  ZAF: { capitalKo: "프리토리아", capitalEn: "Pretoria", langKo: "영어", area: 1221037 },
  ZMB: { capitalKo: "루사카", capitalEn: "Lusaka", langKo: "영어", area: 752612 },
  ZWE: { capitalKo: "하라레", capitalEn: "Harare", langKo: "영어", area: 390757 },
};
